#!/bin/bash 
if [ "$#" -ne 2 ] || [ $1 = '-h' ]
then
    echo "$0 <identite> <intitule certificat>"
    exit 1
fi

if [ -z "$1" ]
then
    echo "Identite non valide"
    exit 1
fi

if [ -z "$2" ]
then
    echo "Intitule certificat non valide"
    exit 1
fi


# curl -X POST -d "identite=$1" -d "intitule_certif=$2" http://localhost:8080/creation

curl -v -X POST -d "identite=$1" -d "intitule_certif=$2" --cacert ../certificat/AC/ecc.ca.cert.pem https://localhost:9000/creation