#!/bin/bash
# Utilisation : ./creer_image texte qrcode nom_fichier_sortie

# Creation de l'image
attestation="Attestion delivré à $1 "
curl -o texte.png "https://dummyimage.com/600x400/ffffff/000000&text=$attestation&font=Arial-Bold"
# Mise en format transparent
convert $2 -transparent white $2
convert texte.png -transparent white texte.png
# Resize de l'image
mogrify -resize 1000x600 texte.png
mogrify -resize 100x100 $2

composite -gravity center texte.png image/fond_attestation.png combinaison.png
# composite -geometry +1418+934 $2 combinaison.png $3
composite -geometry +1468+984 $2 combinaison.png $3


rm texte.png
rm combinaison.png

