#!/bin/bash
# Utilisation : ./creer_image nom prenom qrcode nom_fichier_sortie

# Creation de l'image
attestation="Attestation de réussite\ndélivrée à $1 $2"

mkdir -p "image"

curl -v -o image/fond_attestation.png  http://p-fb.net/fileadmin/fond_attestation.png 

convert -size 1000x600 -gravity center -pointsize 56 label:"$attestation" -transparent white texte.png
# Resize du qrcode
mogrify -resize 100x100 $3

composite -gravity center texte.png image/fond_attestation.png combinaison.png
composite -geometry +1468+984 $3 combinaison.png $4


rm texte.png
rm combinaison.png

