#!/bin/bash 

# if [ "$#" -ne 1 ] || [ $1 = '-h' ]
# then
#     echo "$0 <mon image> "
#     exit 1
# fi

# curl -v -o $1 http://localhost:8080/fond

curl -v -o image/mon_image.png http://localhost:8080/fond
